### ISSUE TITLE
Embeed Vimeo in a popup instead of an external link

### ISSUE THREAD

**Issue by tcitworld** [nicosomb/website-wallabagit#3]

**Comment by nicosomb** [comment]
Can you enable JS please? It's already a popin. 
![capture d ecran 2016-12-10 a 11 40 39](https://cloud.githubusercontent.com/assets/121870/21072756/833bf144-becd-11e6-8141-dc7c29915c56.png)

**Comment by tcitworld** [comment]
My mad, I didn't check right before. It wasn't a few days ago, right ?

**Comment by nicosomb** [comment]
You can check commits, it was here
